title: blackbild.sass library
email: thomduerr@gmail.com
description: >
  A little Sass library for every day usage
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
github_username:  thomd

# Build settings
markdown: kramdown
permalink: none
sass:
  style: compressed
