title: blackbird.sass
email: thomduerr@gmail.com
description: A little SASS library for every day usage
baseurl: "blackbird.sass"
url: "http://thomd.github.io/blackbird.sass"
github_username: thomd

# Build settings
markdown: kramdown
permalink: none
sass:
  style: compressed
